import localFont from "next/font/local";
import "./globals.css";
import { Poppins } from "next/font/google";
import { Unbounded } from "next/font/google";


const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-poppins",
});
const unbounded = Unbounded({
  subsets: ["latin"],
  weight: "500",
  variable: "--font-unbounded",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${unbounded.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
